import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from 'framer-motion'
import Navbar from "../components/Navbar"
import Destination from "../components/Destinations"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const carAnimate = {

    hidden:{
      x:-60
    }
    ,
    visible:{
      x:[0,-10,-20,-30,-40,-50,-60],
      opacity:1,
      transition:{
        repeat:Infinity,
        duration:2
      }
    }
  }
  return (
    <>
      <Head>
        <title>Wonah Shuutle's</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/WONAH_S_SHUTTLE__2_-removebg-preview 3.png" />
      </Head>
     

     <div className='bg-[#3D4957]  flex items-center justify-center p-3 text-white relative'>
      <div className="absolute top-0 right-0 left-0 mb-[60px]"><Navbar/></div>
      
      <motion.div variants={carAnimate} initial="hidden" animate="visible" className='mt-[50px]'><Image src="/5d074804-e0de-4003-a355-9815be301490-removebg-preview 3.png" width={880} height={300} alt="car-image"/></motion.div>

      <div className='bottom-[20px] absolute bg-white p-2 text-[#3D4957] right-[170px] w-[200px] flex items-center justify-center h-[50px]'>
        <h3>Book Now</h3>
      </div>

      <div className='-bottom-[40px] absolute bg-white p-2 text-black right-[570px]  w-[400px] flex items-center justify-around h-[70px] shadow-md'>
      <div>
        <h1 className="font-extrabold">Destination</h1>
        <p className='text-sm'>Elizabeth University</p>
      </div>
      <div>
        <h1 className="font-extrabold">Date</h1>
        <p className='text-sm'>Select date</p>
      </div>
      <div className='bg-[#3D4957] '>
        <Image src="/material-symbols_person-search-rounded.png" width={50} height={100} alt="imafe"/>

      </div>
      </div>
     

     </div>

     <Destination/>

     <div className="h-[400px] relative" style={{background:'url("/Rectangle 20.png")',backgroundSize:'cover',backgroundRepeat:'no-repeat'}}>
      <div className="text-white absolute top-0 right-0 left-0 bottom-0 opacity-[5px] bg-black flex justify-center">
        <div className="flex flex-col gap-3 p-3 items-center mt-[50px]">
        <div>
        <h1>Our Company Informations</h1>
      </div>

      <div>
        <h1>UpComing DropOffs</h1>
      </div>

      <div>
        <h1>Our Company Informations</h1>
      </div>
        </div>

     
      </div>
     


     </div>
       

            
        
    </>
  )
}
